### ISSUE TITLE
Conflicts when fetching axi module

### ISSUE THREAD

**Issue by anga93** [pulp-platform/pulp_soc#18]
when building RTL platform of PULP I get this error:
1. pulp-platform/axi @ v0.7.1 (retrieved from pulp-platform/pulp_soc @ pulp-next)
  2. pulp-platform/axi @ v0.7.0 (retrieved from pulp-platform/axi_node @ v1.1.3)

Since I am using IPApproX tool to generate IP tree, we should update the version of axi fetched from axi_nod ips_list.yml to the same version in the pulp_soc ips_list.yml (i.e. v0.7.1).

**Comment by bluewww** [comment]
agree, I'm making a PR to `axi_node`

**Comment by bluewww** [comment]
See https://github.com/pulp-platform/axi_node/pull/15
