### ISSUE TITLE
Merge `update-hwpe` branch into `master` and then delete the branch?

### ISSUE THREAD

**Issue by vogelpi** [pulp-platform/pulp_soc#48]
Hi @FrancescoConti ,
@micprog just noted that [`pulp`](https://github.com/pulp-platform/pulp/pull/42/files) lo longer references `master` but instead the the `v.1.4.3` tag on the `update-hwpe` branch of `pulp_soc`. This looks bad and could lead to problems and merge madness in later PRs. I think it would be much better to merge the `update-hwpe` branch into `master` and then delete the branch. Or is there a particular reason why not merging it into `master`?

Also pinging the repo owner @bluewww .

**Comment by FrancescoConti** [comment]
Nope, simply a mistake with the missing merge.

**Comment by vogelpi** [comment]
Ah I see. Thanks for your feedback @FrancescoConti . What is your plan now? Do you want to merge `update-hwpe` into `master`? I think if it's properly done, the commit ID/tag should still remain the same.

**Comment by FrancescoConti** [comment]
Yes -- it's simply a version bump so there should be no particular issue. If necessary, we can also push the minor patch tag up one notch. See #49
